spring:
  devtools:
    remote:
      secret: secret@devtools
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:moviesapi
    driverClassName: org.h2.Driver
    username: simaoramos
    password: sr@123
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect